### ISSUE TITLE
nginx: [emerg] unknown "quic" variable

### ISSUE THREAD

**Issue by justinzhf** [yurymuski/nginx-http3#1]
Hi, I read the post https://medium.com/faun/implementing-http3-quic-nginx-99094d3e39f. And I follow the instructions given in the post. Everything goes smoothly except that when I run the docker image, the container exits due to the error "nginx: [emerg] unknown "quic" variable". Can you help me to solve the problem? Thanks a lot!

**Comment by yurymuski** [comment]
Hi, will take a look, probably tomorrow or so

**Comment by yurymuski** [comment]
@justinzhf Hi, just checked and everyting is working fine, dockerfile builds, and nginx executes well. How do you run it?
```
docker run --name nginx -d -p 80:80 -p 443:443/tcp -p 443:443/udp -v /etc/letsencrypt/:/opt/nginx/certs/ -v /opt/nginx/conf/example.nginx.conf:/etc/nginx/nginx.conf ymuski/nginx-quic
```
Note that example.nginx.conf should be updated with your domain and certs

**Comment by yurymuski** [comment]
```
docker run -it --rm ymuski/curl-http3 curl -Lv https://test.yurets.online --http3
```
HTTP/3 200
