### ISSUE TITLE
http3 proxy for end to end usage.

### ISSUE THREAD

**Issue by aguzmans** [yurymuski/nginx-http3#2]
Hi there, this does serve content on http3, but is not end to end http3. DO you know about anything experimental or usable that allows for proxy to http3?

something like:
```
        location / {
            proxy_pass https://example.com;
            (...)
            proxy_http_version 3;
            (..)
        }
```

**Comment by yurymuski** [comment]
Hi, 
nginx patch that I use does not have such config options: https://github.com/cloudflare/quiche/tree/master/extras/nginx#list-of-configuration-directives

There is development of quic in nginx team but there are also no any proxy related directives: https://hg.nginx.org/nginx-quic/file/quic/README#l110
