### ISSUE TITLE
[Feature Request] fork swag w/ dank http/3 support

### ISSUE THREAD

**Issue by Motophan** [yurymuski/nginx-http3#3]
https://github.com/linuxserver/docker-swag

I use this, as it has everything preconfigured for the docker containers. Could you fork this w/ http3 + http2/1.1 support? It's extremely popular and using your container as a drop in replacement would be great. They even setup a DNS TLS challenge acme recurring thing.

**Comment by yurymuski** [comment]
Sorry but docker-swag is not the solution I want to use :)
