### ISSUE TITLE
You don't have to choose this docker anymore. 1: unknown "quic" variable

### ISSUE THREAD

**Issue by rustxj** [yurymuski/nginx-http3#5]
2021/05/07 11:53:27 [emerg] 1#1: unknown "quic" variable
nginx: [emerg] unknown "quic" variable
2021/05/07 11:55:27 [emerg] 1#1: unknown "quic" variable
nginx: [emerg] unknown "quic" variable
2021/05/07 11:57:30 [emerg] 1#1: unknown "quic" variable
nginx: [emerg] unknown "quic" variable

**Comment by yurymuski** [comment]
GET /host HTTP/3" 200

**Comment by yurymuski** [comment]
works well

**Comment by yurymuski** [comment]
docker image: ymuski/nginx-quic
