### ISSUE TITLE
HTTP3 doesn't work

### ISSUE THREAD

**Issue by augustomurri** [yurymuski/nginx-http3#6]
I have some problems QUIC doesn't seem working on this website https://www.udempharma.com

`docker run --name nginx -d -p 80:80 -p 443:443 -v /etc/letsencrypt:/etc/letsencrypt -v /docker/nginx/nginx.conf:/etc/nginx/nginx.conf -v /docker/nginx/conf.d:/etc/nginx/conf.d -v /var/www:/var/www -v /docker/nginx/ssl/dhparam.pem:/etc/nginx/ssl/dhparam.pem -v phpmyadmin_data:/var/www/html ymuski/nginx-quic`

Virtual host directive enabled
`        # Enable QUIC and HTTP/3.
        listen 443 quic reuseport;

        # Enable HTTP/2 (optional).
        listen 443 ssl http2;

        ssl_certificate /etc/letsencrypt/live/udempharma.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/udempharma.com/privkey.pem;
	ssl_trusted_certificate /etc/letsencrypt/live/udempharma.com/chain.pem;
        ssl_session_cache shared:SSL:50m;
        ssl_session_timeout 5m;

        # Enable all TLS versions (TLSv1.3 is required for QUIC).
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;

        # Add Alt-Svc header to negotiate HTTP/3.
        #add_header alt-svc 'h3=":443"; ma=86400';
	add_header alt-svc 'h3-28=":443"; ma=86400';
	add_header X-Cache $upstream_cache_status;
`
Nginx correctly running, firewall is disabled

[https://www.http3check.net/?host=https%3A%2F%2Fwww.udempharma.com%2F](https://www.http3check.net/?host=https%3A%2F%2Fwww.udempharma.com%2F)

**Server does not advertise supported HTTP/3 or QUIC version on the same port.**

`docker run -it --rm ymuski/curl-http3 curl -ILv https://www.udempharma.com --http3
*   Trying 116.203.83.243:443...
* Connect socket 5 over QUIC to 116.203.83.243:443
* Sent QUIC client Initial, ALPN: h3-29,h3-28,h3-27
* quiche: recv() unexpectedly returned -1 (errno: 111, socket 5)
* connect to 116.203.83.243 port 443 failed: Connection refused
* Failed to connect to www.udempharma.com port 443: Connection refused
* Closing connection 0
curl: (7) quiche: recv() unexpectedly returned -1 (errno: 111, socket 5)
`

**Comment by yurymuski** [comment]
Hi @augustomurri 
as I see from response from your site you use incorrect header: 
`alt-svc h3=":443"` it shoud be at least `alt-svc 'h3=":443"; ma=86400';`
Can you share nginx configs?
Important parts are:
```nginx
listen 443 quic reuseport;
ssl_early_data on;
ssl_protocols TLSv1.3;
add_header alt-svc 'h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400';
```

**Comment by yurymuski** [comment]
I have updated docker image to latest quiche patch, now its possible to set just `add_header alt-svc 'h3=":443"; ma=86400';`

You can add some simple route for testing:
```nginx
        location /host {
            return 200 "http3 on $hostname";
            add_header Content-Type text/plain;
            add_header alt-svc 'h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400, h3=":443"; ma=86400';
        }
```

**Comment by yurymuski** [comment]
I've setup demo site: <a href="https://http3.yurets.pro" target="_blank">http3.yurets.pro</a> you can check it.

**Comment by augustomurri** [comment]
Hi @yurymuski , i am doing something wrong but i don't understand. I applied you rules.

Also i stopped and removed the container, deleted the local image version and download the new.

I didn't use your Dockerfile

This is my udempharma.com.conf

`
fastcgi_cache_path /var/cache/nginx/udempharma.com levels=1:2 keys_zone=WORDPRESS_udempharma.com:100m inactive=60m;

server {
        listen       80;
        server_name  www.udempharma.com udempharma.com;
        rewrite ^ https://$http_host$request_uri? permanent;    # force redirect http to https
}

server {
        listen 443 quic reuseport;
        listen 443 ssl http2;

        ssl_certificate /etc/letsencrypt/live/udempharma.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/udempharma.com/privkey.pem;
	ssl_trusted_certificate /etc/letsencrypt/live/udempharma.com/chain.pem;
        ssl_session_cache shared:SSL:50m;
        ssl_session_timeout 5m;
	ssl_early_data on;

        # Enable all TLS versions (TLSv1.3 is required for QUIC).
	ssl_protocols TLSv1.3;

        # Add Alt-Svc header to negotiate HTTP/3.
	add_header alt-svc 'h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400';
	add_header X-Cache $upstream_cache_status;

        server_name www.udempharma.com udempharma.com;

	root /var/www/udempharma.com/;
        index index.php index.html;

        error_log  off; #  /var/log/nginx/udempharma.error.log notice;
        access_log off; #  /var/log/nginx/udempharma.it.access.log;

        rewrite ^/wp-content/cache/minify/ /index.php last;

        set $no_cache 0;
        if ($request_method = POST) { set $no_cache 1; }
        if ($request_uri ~* "(\/wp-admin\/|wp-.*\.php|index\.php|wp\-locations\.php)") { set $no_cache 1; }
        if ($request_uri ~* "account|wishlist|carrello|checkout|order-received") { set $no_cache 1; }
        if ($http_cookie ~* "comment_author|wordpress_[a-f0-9]+|wp-postpass|wordpress_no_cache|wordpress_logged_in|woocommerce_items_in_cart") { set $no_cache 1; }

        location ~* /xmlrpc.php { deny all; access_log off; log_not_found off; }
        location ~*.(ogg|ogv|svg|svgz|eot|otf|woff|woff2|mp4|ttf|css|rss|atom|js|jpg|jpeg|gif|png|ico|zip|tgz|gz|rar|bz2|doc|xls|exe|ppt|tar|mid|midi|wav|bmp|rtf|cur)$ { expires max; log_not_found off; access_log off; }
        location ~* wp-config.php { deny all; }
        location = /robots.txt { access_log off; log_not_found off; }
        location ~ /\.ht { access_log off; log_not_found off; }
        location /nginx_status { stub_status on; access_log off; log_not_found off; }

	location /http3 {
            return 200 "http3 on $hostname";
            add_header Content-Type text/plain;
            add_header alt-svc 'h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400, h3=":443"; ma=86400';
        }

        location / {
                try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$ {
                try_files $uri =404;
                include fastcgi_params;
                fastcgi_pass 172.17.0.3:9000;
                fastcgi_split_path_info ^(.+\.php)(.*)$;
                fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_read_timeout 900;

                fastcgi_cache_bypass $no_cache;
                fastcgi_no_cache $no_cache;

                fastcgi_cache WORDPRESS_udempharma.com;
                fastcgi_cache_valid 200 301 302 1w;
                fastcgi_cache_use_stale updating error timeout invalid_header http_500;

                fastcgi_pass_header Set-Cookie;
                fastcgi_pass_header Cookie;
                fastcgi_ignore_headers Cache-Control Expires Set-Cookie;
	}
}
`

nginx.conf

`
user nginx;
worker_processes auto;
pid /run/nginx.pid;

 http {

        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        # server_tokens off;

        # server_names_hash_bucket_size 64;
        # server_name_in_redirect off;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ##
        # GeoBlock
        ##
        #geoip_country /usr/share/GeoIP/GeoIP.dat;
        #map $geoip_country_code $allowed_country {
        #        default yes;
        #        RU no;
        #        CN no;
        #        KOR no;
        #}

        ##
        # Custom Murri
        ##
        client_max_body_size 50m;
        client_body_buffer_size 128k;
        client_body_timeout 3m;
        client_header_timeout 3m;
        client_header_buffer_size    1k;
        large_client_header_buffers  4 4k;
        output_buffers               1 32k;
        postpone_output              1460;
        send_timeout 3m;

        proxy_buffer_size   128k;
        proxy_buffers   4 256k;
        proxy_busy_buffers_size   256k;

        fastcgi_buffers 256 16k;
        fastcgi_buffer_size 128k;
        fastcgi_connect_timeout 3s;
        fastcgi_send_timeout 120s;
        fastcgi_read_timeout 120s;
        fastcgi_busy_buffers_size 256k;
        fastcgi_temp_file_write_size 256k;
        reset_timedout_connection on;

        open_file_cache max=2000 inactive=20s;
        open_file_cache_valid 60s;
        open_file_cache_min_uses 5;
        open_file_cache_errors off;

        ##
        # Direttive comuni su FASTCGI_CACHE
        ##

        fastcgi_cache_key "$scheme$request_method$host$request_uri";
        fastcgi_cache_use_stale error timeout invalid_header http_500;
        fastcgi_ignore_headers Cache-Control Expires Set-Cookie;

        ##
        # SSL Settings
        ##

        #ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
        ssl_dhparam /etc/nginx/ssl/dhparam.pem;
        ssl_prefer_server_ciphers on;


        ##
        # Logging Settings
        ##

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
        #access_log off;
        #error_log off;

	##
	# Brotli Settings
	##

	brotli     on;
	brotli_static        on;
	brotli_comp_level          6;
	brotli_types         application/rss+xml application/xhtml+xml
	text/css text/plain;

        ##
        # Gzip Settings
        ##

        gzip on;
        gzip_http_version  1.1;
        gzip_comp_level    8;
        gzip_min_length    256;
        gzip_proxied       any;
        gzip_vary          on;
        gzip_types
                        application/atom+xml
                        application/javascript
                        application/json
                        application/rss+xml
                        application/vnd.ms-fontobject
                        application/x-font-ttf
                        application/x-web-app-manifest+json
                        application/xhtml+xml
                        application/xml
                        text/javascript
                        font/opentype
                        image/svg+xml
                        image/x-icon
                        text/css
                        text/plain
                        text/x-component;
                        # text/html is always compressed by HttpGzipModule


        ##
        # Virtual Host Configs
        ##

        include /etc/nginx/conf.d/*.conf;

}
`

**Comment by yurymuski** [comment]
your config looks correct
so the issue is somewhere before nginx
curl response is obvious:
```
docker run -it --rm ymuski/curl-http3 curl -ILv https://www.udempharma.com/http3 --http3
*   Trying 116.203.83.243:443...
* Connect socket 5 over QUIC to 116.203.83.243:443
* Sent QUIC client Initial, ALPN: h3-29,h3-28,h3-27
* quiche: recv() unexpectedly returned -1 (errno: 111, socket 5)
* connect to 116.203.83.243 port 443 failed: Connection refused
* Failed to connect to www.udempharma.com port 443: Connection refused
* Closing connection 0
curl: (7) quiche: recv() unexpectedly returned -1 (errno: 111, socket 5)

```

Seems you have some FW issues
udp does not work:
`nc -v -u 116.203.83.243 443`

**Comment by augustomurri** [comment]
I have restarted the container using -p 443:443/tcp -p 443:443/udp and now ports are enabled.
I don't no why it doesn't work, there are no firewal blocks, ufw inactive, ports opened. is a clean instance

from another instance
```
nc -v -u udempharma.com 443
udempharma.com [116.203.83.243] 443 (?) open
```

```
root@OdooUdemPharma:~# iptables -S
-P INPUT DROP
-P FORWARD DROP
-P OUTPUT ACCEPT
-N f2b-sshd
-N DOCKER
-N DOCKER-ISOLATION-STAGE-1
-N DOCKER-ISOLATION-STAGE-2
-N DOCKER-USER
-N ufw-before-logging-input
-N ufw-before-logging-output
-N ufw-before-logging-forward
-N ufw-before-input
-N ufw-before-output
-N ufw-before-forward
-N ufw-after-input
-N ufw-after-output
-N ufw-after-forward
-N ufw-after-logging-input
-N ufw-after-logging-output
-N ufw-after-logging-forward
-N ufw-reject-input
-N ufw-reject-output
-N ufw-reject-forward
-N ufw-track-input
-N ufw-track-output
-N ufw-track-forward
-N ufw-logging-deny
-N ufw-logging-allow
-N ufw-skip-to-policy-input
-N ufw-skip-to-policy-output
-N ufw-skip-to-policy-forward
-N ufw-not-local
-N ufw-user-input
-N ufw-user-output
-N ufw-user-forward
-N ufw-user-logging-input
-N ufw-user-logging-output
-N ufw-user-logging-forward
-N ufw-user-limit
-N ufw-user-limit-accept
-A INPUT -p tcp -m multiport --dports 22 -j f2b-sshd
-A INPUT -j ufw-before-logging-input
-A INPUT -j ufw-before-input
-A INPUT -j ufw-after-input
-A INPUT -j ufw-after-logging-input
-A INPUT -j ufw-reject-input
-A INPUT -j ufw-track-input
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION-STAGE-1
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -j ufw-before-logging-forward
-A FORWARD -j ufw-before-forward
-A FORWARD -j ufw-after-forward
-A FORWARD -j ufw-after-logging-forward
-A FORWARD -j ufw-reject-forward
-A FORWARD -j ufw-track-forward
-A OUTPUT -j ufw-before-logging-output
-A OUTPUT -j ufw-before-output
-A OUTPUT -j ufw-after-output
-A OUTPUT -j ufw-after-logging-output
-A OUTPUT -j ufw-reject-output
-A OUTPUT -j ufw-track-output
-A f2b-sshd -j RETURN
-A DOCKER -d 172.17.0.2/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 3306 -j ACCEPT
-A DOCKER -d 172.17.0.5/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 80 -j ACCEPT
-A DOCKER -d 172.17.0.3/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 9000 -j ACCEPT
-A DOCKER -d 172.17.0.4/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 443 -j ACCEPT
-A DOCKER -d 172.17.0.4/32 ! -i docker0 -o docker0 -p udp -m udp --dport 443 -j ACCEPT
-A DOCKER -d 172.17.0.4/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 80 -j ACCEPT
-A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -j RETURN
-A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -j RETURN
-A DOCKER-USER -j RETURN
-A ufw-before-input -i lo -j ACCEPT
-A ufw-before-input -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A ufw-before-input -m conntrack --ctstate INVALID -j ufw-logging-deny
-A ufw-before-input -m conntrack --ctstate INVALID -j DROP
-A ufw-before-input -p icmp -m icmp --icmp-type 3 -j ACCEPT
-A ufw-before-input -p icmp -m icmp --icmp-type 11 -j ACCEPT
-A ufw-before-input -p icmp -m icmp --icmp-type 12 -j ACCEPT
-A ufw-before-input -p icmp -m icmp --icmp-type 8 -j ACCEPT
-A ufw-before-input -p udp -m udp --sport 67 --dport 68 -j ACCEPT
-A ufw-before-input -j ufw-not-local
-A ufw-before-input -d 224.0.0.251/32 -p udp -m udp --dport 5353 -j ACCEPT
-A ufw-before-input -d 239.255.255.250/32 -p udp -m udp --dport 1900 -j ACCEPT
-A ufw-before-input -j ufw-user-input
-A ufw-before-output -o lo -j ACCEPT
-A ufw-before-output -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A ufw-before-output -j ufw-user-output
-A ufw-before-forward -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A ufw-before-forward -p icmp -m icmp --icmp-type 3 -j ACCEPT
-A ufw-before-forward -p icmp -m icmp --icmp-type 11 -j ACCEPT
-A ufw-before-forward -p icmp -m icmp --icmp-type 12 -j ACCEPT
-A ufw-before-forward -p icmp -m icmp --icmp-type 8 -j ACCEPT
-A ufw-before-forward -j ufw-user-forward
-A ufw-after-input -p udp -m udp --dport 137 -j ufw-skip-to-policy-input
-A ufw-after-input -p udp -m udp --dport 138 -j ufw-skip-to-policy-input
-A ufw-after-input -p tcp -m tcp --dport 139 -j ufw-skip-to-policy-input
-A ufw-after-input -p tcp -m tcp --dport 445 -j ufw-skip-to-policy-input
-A ufw-after-input -p udp -m udp --dport 67 -j ufw-skip-to-policy-input
-A ufw-after-input -p udp -m udp --dport 68 -j ufw-skip-to-policy-input
-A ufw-after-input -m addrtype --dst-type BROADCAST -j ufw-skip-to-policy-input
-A ufw-after-logging-input -m limit --limit 3/min --limit-burst 10 -j LOG --log-prefix "[UFW BLOCK] "
-A ufw-after-logging-forward -m limit --limit 3/min --limit-burst 10 -j LOG --log-prefix "[UFW BLOCK] "
-A ufw-track-output -p tcp -m conntrack --ctstate NEW -j ACCEPT
-A ufw-track-output -p udp -m conntrack --ctstate NEW -j ACCEPT
-A ufw-logging-deny -m conntrack --ctstate INVALID -m limit --limit 3/min --limit-burst 10 -j RETURN
-A ufw-logging-deny -m limit --limit 3/min --limit-burst 10 -j LOG --log-prefix "[UFW BLOCK] "
-A ufw-logging-allow -m limit --limit 3/min --limit-burst 10 -j LOG --log-prefix "[UFW ALLOW] "
-A ufw-skip-to-policy-input -j DROP
-A ufw-skip-to-policy-output -j ACCEPT
-A ufw-skip-to-policy-forward -j DROP
-A ufw-not-local -m addrtype --dst-type LOCAL -j RETURN
-A ufw-not-local -m addrtype --dst-type MULTICAST -j RETURN
-A ufw-not-local -m addrtype --dst-type BROADCAST -j RETURN
-A ufw-not-local -m limit --limit 3/min --limit-burst 10 -j ufw-logging-deny
-A ufw-not-local -j DROP
-A ufw-user-input -p tcp -m tcp --dport 2222 -j ACCEPT
-A ufw-user-input -p tcp -m tcp --dport 80 -j ACCEPT
-A ufw-user-input -p tcp -m tcp --dport 8069 -j ACCEPT
-A ufw-user-input -p udp -m udp --dport 8069 -j ACCEPT
-A ufw-user-input -p udp -m udp --dport 443 -j ACCEPT
-A ufw-user-input -p tcp -m tcp --dport 443 -j ACCEPT
-A ufw-user-limit -m limit --limit 3/min -j LOG --log-prefix "[UFW LIMIT BLOCK] "
-A ufw-user-limit -j REJECT --reject-with icmp-port-unreachable
-A ufw-user-limit-accept -j ACCEPT
```


```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      3419/docker-proxy   
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      3378/docker-proxy   
tcp6       0      0 :::80                   :::*                    LISTEN      3424/docker-proxy   
tcp6       0      0 :::443                  :::*                    LISTEN      3384/docker-proxy   
udp        0      0 0.0.0.0:443             0.0.0.0:*                           3398/docker-proxy   
udp6       0      0 :::443                  :::*                                3403/docker-proxy   
```

```
ufw status
Status: active

To                         Action      From
--                         ------      ----
2222/tcp                   ALLOW       Anywhere                  
80/tcp                     ALLOW       Anywhere                  
8069                       ALLOW       Anywhere                  
443/udp                    ALLOW       Anywhere                  
443/tcp                    ALLOW       Anywhere                  
2222/tcp (v6)              ALLOW       Anywhere (v6)             
80/tcp (v6)                ALLOW       Anywhere (v6)             
8069 (v6)                  ALLOW       Anywhere (v6)             
443/udp (v6)               ALLOW       Anywhere (v6)             
443/tcp (v6)               ALLOW       Anywhere (v6) 
```
i always get connection timeout fff

**Comment by yurymuski** [comment]
Hey, seems all works now

```sh
docker run -it --rm ymuski/curl-http3 curl -ILv https://www.udempharma.com/http3 --http3
# HTTP/3 200
```
Http3 check also: https://www.http3check.net/?host=https%3A%2F%2Fwww.udempharma.com%2F
Congrats)
Have you changed anything else?
Or it was only header + FW fix
![image](https://user-images.githubusercontent.com/20399073/124750453-265c3980-df2e-11eb-856e-969bdcfe008d.png)

**Comment by augustomurri** [comment]
Hi Yuri, nope didn't change anything! Maybe some problems related to FastCGI cache 
Thanks for support

**Comment by yurymuski** [comment]
@augustomurri  please add star to the repo so :D

**Comment by augustomurri** [comment]
I think it can  be the TOP if you enable the GeoIp module, usually used to prevent bots and brute force traffic
https://docs.nginx.com/nginx/admin-guide/security-controls/controlling-access-by-geoip/

**Comment by yurymuski** [comment]
It needs NGINX Plus or compile with this one https://github.com/leev/ngx_http_geoip2_module
Not sure that geo is pretty useful by itself, you can block ip or usearagent, I have never blocked by country/city :D

Anyway I use openresty + geoip+lua in this one https://github.com/yurymuski/geo-checker
maybe it makes sense to add geoip+lua here. Will see

**Comment by augustomurri** [comment]
Never used OpenResty i'll take a look and try ;)

I think geoblocking is an important feature, i usually use it to prevent bad traffic from east asia, depend of what kind of software you need to run. It's a very usefull cloudflare feature
